language: python
python:
  - '3.6'

services:
  - postgresql

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=flaskrestorders
    - DB_USER=postgres
    - DB_PASSWORD=

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database flaskrestorders;' -U postgres
  - python run.py &  # start a Web server in the background
  - sleep 3 # give Web server some time to bind to sockets, etc

# command to run tests
script:
  - pytest
  - behave

after_success:
 - codecov
